name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
        
    - name: Pruebas y generación de cobertura
      id: pruebas
      run: |
        python -m coverage run -m unittest discover tests
        python -m coverage report
        python -m coverage xml -o coverage.xml
        sed -i 's|/home/runner/work/Tutorial-Canciones/Tutorial-Canciones/||g' coverage.xml

    - name: Verificar archivo coverage.xml
      run: cat coverage.xml
      
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}